kind: Service
apiVersion: v1
metadata:
  name: kibana-logging-external
  namespace: kube-system
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32383
  selector:
    k8s-app: kibana-logging
